#!/usr/bin/env bash
# ZWAN-AGENT installer — creates venv, installs deps.
# Optionally installs a sudoers drop-in for NOPASSWD operation.
# NEVER writes /etc/sudoers.d without explicit interactive 'yes'.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_DIR="$SCRIPT_DIR/agent"
VENV="$AGENT_DIR/.venv"
SUDOERS_FILE="/etc/sudoers.d/zwan-agent"
SUDOERS_DROPIN="# ZWAN-AGENT: NOPASSWD for authorized security tools only
# Generated by install.sh — review before accepting
$(whoami) ALL=(root) NOPASSWD: /usr/bin/nmap, /usr/sbin/nmap, /usr/bin/masscan, /usr/bin/naabu, /usr/sbin/tcpdump, /usr/bin/tcpdump"

echo ""
echo "=== ZWAN-CODEX v2.1 — Agent Installer ==="
echo ""

# ── Python venv ───────────────────────────────────────────────────────────────

if [ ! -d "$VENV" ]; then
  echo "[*] Creating Python venv in $VENV …"
  python3 -m venv "$VENV"
fi

echo "[*] Installing agent dependencies…"
"$VENV/bin/pip" install -q --upgrade pip
"$VENV/bin/pip" install -q \
  fastapi "uvicorn[standard]" websockets \
  pyyaml aiosqlite anthropic httpx \
  playwright \
  pytest pytest-asyncio

echo "[+] Python dependencies installed."

echo "[*] Installing chromium for Playwright (one-time ~280MB)…"
"$VENV/bin/python" -m playwright install chromium
echo "[+] Chromium installed."

# ── askpass executable ────────────────────────────────────────────────────────

chmod +x "$AGENT_DIR/askpass.sh"
echo "[+] askpass.sh is executable."

# ── Tests ─────────────────────────────────────────────────────────────────────

echo ""
echo "[*] Running safety core tests…"
cd "$AGENT_DIR"
"$VENV/bin/python" -m pytest tests/ -q
cd "$SCRIPT_DIR"
echo "[+] All tests passed."

# ── Sudoers drop-in (optional, explicit yes required) ────────────────────────

echo ""
echo "=== Optional: sudoers NOPASSWD hardening ==="
echo ""
echo "This creates $SUDOERS_FILE granting NOPASSWD ONLY for:"
echo "  nmap, masscan, naabu, tcpdump"
echo "This removes the interactive sudo password prompt for these tools."
echo "It is validated with 'visudo -c' before writing."
echo ""
printf "Install sudoers drop-in? [yes/NO]: "
read -r ANSWER

if [ "$ANSWER" = "yes" ]; then
  TMP=$(mktemp)
  echo "$SUDOERS_DROPIN" > "$TMP"
  if visudo -c -f "$TMP" 2>&1; then
    if sudo cp "$TMP" "$SUDOERS_FILE" && sudo chmod 440 "$SUDOERS_FILE"; then
      echo "[+] Sudoers drop-in installed at $SUDOERS_FILE"
    else
      echo "[!] Failed to copy sudoers file — check sudo permissions."
    fi
  else
    echo "[!] visudo validation failed — NOT writing sudoers file."
  fi
  rm -f "$TMP"
else
  echo "[*] Skipped. You can re-run install.sh to add it later."
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Setup complete ==="
echo ""
echo "Start the agent:"
echo "  ANTHROPIC_API_KEY=sk-... $VENV/bin/python -m agent.main"
echo ""
echo "Optional Ollama fallback:"
echo "  OLLAMA_HOST=http://127.0.0.1:11434 $VENV/bin/python -m agent.main"
echo ""
echo "Then open the Console tab in ZWAN-CODEX (port 3001)."
echo "Copy the token printed on agent startup into the Connect input."
echo ""
