"""RaceAgent — identifies race-condition targets, generates Turbo Intruder scripts."""
from __future__ import annotations

import json
import uuid
from pathlib import Path
from urllib.parse import urlparse

import httpx

from app.agents.base import BaseAgent
from app.agents.orchestrator import register_agent
from app.config import settings
from app.db.models import Asset, Finding, FindingStatus, Severity

_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "race.md"

_RACE_INDICATORS = [
    # Voucher / coupon
    ("voucher", "redeem"), ("coupon", "apply"), ("promo", "use"),
    # Payment / transfer
    ("payment", "process"), ("transfer", "send"), ("withdraw", ""),
    # Bonus / referral
    ("referral", "claim"), ("bonus", "activate"), ("reward", ""),
    # Vote / rating
    ("vote", ""), ("like", ""), ("rating", "submit"),
    # Signup / activation
    ("register", ""), ("verify", ""), ("activate", ""),
]

_TURBO_TEMPLATE = '''# Turbo Intruder script — Race Condition PoC
# Target: {url}  Method: {method}
# Generated by ZWAN-CODEX-V2 RaceAgent

def queueRequests(target, wordlists):
    engine = RequestEngine(
        endpoint=target.endpoint,
        concurrentConnections=1,
        requestsPerConnection=30,
        pipeline=False,
        engine=Engine.BURP2
    )
    for i in range(30):
        engine.queue(target.req, str(i))

def handleResponse(req, interesting):
    table.add(req)

# Raw request to paste into Turbo Intruder:
# {method} {path} HTTP/1.1
# Host: {host}
# Content-Type: application/json
#
# {body}
'''


@register_agent
class RaceAgent(BaseAgent):
    name = "race"

    async def _execute(self) -> dict:
        scope_urls: list[str] = self.engagement.scope_urls
        candidates: list[dict] = []

        for base_url in scope_urls:
            await self._emit("trace", {"message": f"Race scan: {base_url}"})
            found = await self._find_race_candidates(base_url)
            candidates.extend(found)
            await self._emit("trace", {"message": f"{base_url}: {len(found)} race candidates"})

        if not candidates:
            await self._emit("trace", {"message": "No race condition candidates found"})
            return {"candidates": 0}

        # LLM analysis to prioritize
        analysis_prompt = (
            f"These endpoints look like race condition candidates:\n{json.dumps(candidates, indent=2)}\n\n"
            "For each, rate the likelihood of a race condition (high/medium/low) and explain the impact."
        )
        try:
            analysis, _ = await self.llm.complete(
                model=settings.llm_mid,
                system=_PROMPT_PATH.read_text(),
                messages=[{"role": "user", "content": analysis_prompt}],
                max_tokens=2048,
            )
            await self._emit("trace", {"message": "LLM race analysis complete"})
        except Exception as e:
            analysis = f"LLM analysis failed: {e}"

        # Generate Turbo Intruder scripts and persist findings for high-priority targets
        high_priority = candidates[:5]  # top 5
        for c in high_priority:
            script = _TURBO_TEMPLATE.format(
                url=c["url"],
                method=c["method"],
                path=urlparse(c["url"]).path,
                host=urlparse(c["url"]).hostname,
                body=json.dumps(c.get("sample_body", {})),
            )
            finding = Finding(
                id=str(uuid.uuid4()),
                engagement_id=self.engagement.id,
                title=f"Potential Race Condition — {c['url']}",
                severity=Severity.MEDIUM,
                status=FindingStatus.NEEDS_REVIEW,
                description=f"State-mutating endpoint susceptible to race condition: {c['url']}",
                reproducer=script,
                impact="Race condition may allow double-spend, multiple voucher redemption, or duplicate resource creation.",
                meta={"candidate": c, "turbo_intruder_script": script},
            )
            self.db.add(finding)
        await self.db.commit()

        await self._emit("trace", {"message": f"Race done: {len(candidates)} candidates, {len(high_priority)} scripts generated"})
        return {"candidates": len(candidates), "scripts_generated": len(high_priority)}

    async def _find_race_candidates(self, base_url: str) -> list[dict]:
        candidates: list[dict] = []
        async with httpx.AsyncClient(timeout=8, follow_redirects=False) as client:
            # Discover via crawl-like path probing
            common_paths = [
                "/api/voucher/redeem", "/api/coupon/apply", "/api/referral/claim",
                "/api/vote", "/api/like", "/api/payment/process",
                "/api/transfer", "/api/withdraw", "/api/register",
                "/redeem", "/apply", "/claim", "/vote",
            ]
            for path in common_paths:
                url = base_url.rstrip("/") + path
                try:
                    r = await client.get(url)
                    if r.status_code not in (404, 410):
                        candidates.append({
                            "url": url,
                            "method": "POST",
                            "status": r.status_code,
                            "sample_body": self._guess_body(path),
                        })
                except Exception:
                    pass
        return candidates

    def _guess_body(self, path: str) -> dict:
        if "voucher" in path or "coupon" in path or "promo" in path:
            return {"code": "TESTCODE123"}
        if "vote" in path or "like" in path:
            return {"item_id": "1"}
        if "transfer" in path or "payment" in path:
            return {"amount": 1, "to": "attacker"}
        return {}
